services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: heni_user
      POSTGRES_PASSWORD: GUCLU_SIFRE
      POSTGRES_DB: heni_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U heni_user -d heni_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Kullanıcı yüklü dosyalar kalıcı kalsın
      - uploads:/app/static/upload
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  uploads:
